events {
}

http {
    access_log /dev/stdout;
    error_log /dev/stderr warn;

    server {
        # Port listened to by NGINX (HTTP).
        listen 80;

        # Root directory from which website files are served.
        root	/var/www/html;
		index	index.html;
    }
}
