events {
}

http {
    access_log /dev/stdout;
    error_log /dev/stderr warn;

    server {
        # Port where NGINX listens for incoming HTTP requests.
        # Port 80 is the default HTTP port.
        listen 80;

        # Directory containing the website file.
        # NGINX will search for requested files inside this folder.
        root	/var/www/html;
		index	index.html;
    }
}
